feat: AVRO schema and i18n example
emqx/emqx-plugin-template pull request #126
Opened 2024-05-06 07:09 UTC by JimMoen

2024-05-06 07:15 UTC, JimMoen commented
CI failed temporarily, re-run failed check after `emqx/emqx:v5.7.0` tagged

2024-05-09 08:47 UTC, zmstone requested changes
Missing information:

1. Plugin config format (AVRO JSON)
2. Plugin config file initial location
3. Plugin run-time update REST API (maybe provide a `curl` example).
4. UI aid is only available in Enterprise ediition.

2024-05-09 08:50 UTC, zmstone commented
Add some get_config example.
Also describe config life-cycle, when is config loaded, before plugin app start/2 callback or after etc.

2024-05-14 10:52 UTC, zmstone commented on rebar_template.config
> +    {emqx_plugrel, {git, "https://github.com/emqx/emqx_plugrel.git", {tag, "0.4.0"}}}
```suggestion
    {emqx_plugrel, {git, "https://github.com/emqx/emqx_plugrel.git", {tag, "0.4.1"}}}
```

2024-05-16 09:06 UTC, zhongwencool commented on priv/config_schmea.avsc.example
> +{
This file is `config_schema.avsc.example` not `schmea` ?

2024-05-17 04:56 UTC, zmstone commented
the default config should continue to be hocon.
Remember: hocon is super-set of JSON.

EMQX should type-check the config with avro schema if the schema exists. Otherwise just load it as-is

2024-05-22 06:08 UTC, HJianBo approved these changes

2024-05-22 07:34 UTC, HJianBo approved these changes

2024-05-22 08:00 UTC, zmstone approved these changes

2024-05-22 08:01 UTC, JimMoen commented on emqx-plugin.template
> +    {emqx_vsn, "v5.6.1", "EMQX version to use as a dependency."},
Will be updated when v5.7.0 released

2024-05-22 08:01 UTC, merged